# Tugas 6 - Sistem pencarian dokumen menggunakan Singular Value Decomposition (SVD)

**Nama : Achmad Baharuddin Akbar**

**NIM  : 210411100001**


- sistem pencarian dokumen
- reduksi dimensi dengan SVD
- data baru juga di reduksi
- mencari kemiripan ecludian distance

In [10]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [11]:
import re
import string
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

import nltk
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [12]:
import pandas as pd

data_path = ("/content/drive/My Drive/PPW-A/report/tugas-ppw/hasil_preprocesing.csv")
news_data = pd.read_csv(data_path)

news_data

,judul,tanggal,isi,kategori,cleansing,case_folding,tokenize,Filtering/stopword removal
0,"Soroti Kekurangan Nakes, Prabowo Minta India K...","Kamis, 21 Nov 2024 09:31 WIB",Jakarta - Presiden Republik Indonesia Prabowo ...,Kesehatan,Jakarta Presiden Republik Indonesia Prabowo S...,jakarta presiden republik indonesia prabowo s...,"['jakarta', 'presiden', 'republik', 'indonesia...",jakarta presiden republik indonesia prabowo su...
1,Mayapada Hospital Bisa Tangani Bengkak Pasca T...,"Kamis, 21 Nov 2024 09:06 WIB",Jakarta - Mayapada Hospital menawarkan solusi ...,Kesehatan,Jakarta Mayapada Hospital menawarkan solusi p...,jakarta mayapada hospital menawarkan solusi p...,"['jakarta', 'mayapada', 'hospital', 'menawarka...",jakarta mayapada hospital menawarkan solusi pe...
2,"Jangan Sampai Keliru, Ini Beda Nyeri Punggung ...","Kamis, 21 Nov 2024 09:01 WIB",Jakarta - Saraf kejepit menjadi suatu masalah ...,Kesehatan,Jakarta Saraf kejepit menjadi suatu masalah y...,jakarta saraf kejepit menjadi suatu masalah y...,"['jakarta', 'saraf', 'kejepit', 'menjadi', 'su...",jakarta saraf kejepit diabaikan berdampak seri...
3,"Heboh Pejabat di Swedia Punya Fobia Aneh, Taku...","Kamis, 21 Nov 2024 08:31 WIB",Jakarta - Seorang menteri Swedia yang punya ke...,Kesehatan,Jakarta Seorang menteri Swedia yang punya ket...,jakarta seorang menteri swedia yang punya ket...,"['jakarta', 'seorang', 'menteri', 'swedia', 'y...",jakarta menteri swedia ketakutan pisang bahan ...
4,Mayapada Hospital Punya Teknologi VABB untuk B...,"Kamis, 21 Nov 2024 08:14 WIB",Jakarta - Mayapada Hospital menawarkan teknolo...,Kesehatan,Jakarta Mayapada Hospital menawarkan teknolog...,jakarta mayapada hospital menawarkan teknolog...,"['jakarta', 'mayapada', 'hospital', 'menawarka...",jakarta mayapada hospital menawarkan teknologi...
...,...,...,...,...,...,...,...,...
95,Jijik! Supermarket Ini Penuh Bangkai Tikus dan...,"Selasa, 19 Nov 2024 17:00 WIB",Jakarta - Supermarket seharusnya bersih. Tetap...,Kuliner,Jakarta Supermarket seharusnya bersih Tetapi ...,jakarta supermarket seharusnya bersih tetapi ...,"['jakarta', 'supermarket', 'seharusnya', 'bers...",jakarta supermarket bersih supermarket dipenuh...
96,"Mike Tyson Tetap Bugar di Usia 58 Tahun, Ini M...","Selasa, 19 Nov 2024 16:30 WIB",Jakarta - Mike Tyson kembali menyorot perhatia...,Kuliner,Jakarta Mike Tyson kembali menyorot perhatian...,jakarta mike tyson kembali menyorot perhatian...,"['jakarta', 'mike', 'tyson', 'kembali', 'menyo...",jakarta mike tyson menyorot perhatian bertarun...
97,5 Pengunjung Resto Ini Kena Denda Puluhan Juta...,"Selasa, 19 Nov 2024 16:00 WIB",Jakarta - Karena dipicu berbagai alasan dan se...,Kuliner,Jakarta Karena dipicu berbagai alasan dan seb...,jakarta karena dipicu berbagai alasan dan seb...,"['jakarta', 'karena', 'dipicu', 'berbagai', 'a...",jakarta dipicu alasan pengunjung resto dikenak...
98,Canggih! Kini Susu Basi Bisa Dideteksi via Pon...,"Selasa, 19 Nov 2024 15:00 WIB",Jakarta - Kecanggihan teknologi kini membuat d...,Kuliner,Jakarta Kecanggihan teknologi kini membuat de...,jakarta kecanggihan teknologi kini membuat de...,"['jakarta', 'kecanggihan', 'teknologi', 'kini'...",jakarta kecanggihan teknologi deteksi susu bas...
99,Kocak! Bule Ini Sebut Pecel Lele Sebagai Kadal...,"Selasa, 19 Nov 2024 14:30 WIB",Jakarta - Pesan steak ayam via aplikasi ojek o...,Kuliner,Jakarta Pesan steak ayam via aplikasi ojek on...,jakarta pesan steak ayam via aplikasi ojek on...,"['jakarta', 'pesan', 'steak', 'ayam', 'via', '...",jakarta pesan steak ayam via aplikasi ojek onl...

In [13]:
# Ambil kolom dokumen berita
documents = news_data['Filtering/stopword removal'].tolist()

**TF-IDF (Term Frequency-Inverse Document Frequency)**

In [14]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import TruncatedSVD
from sklearn.metrics.pairwise import euclidean_distances
import pandas as pd
import numpy as np
import joblib

In [15]:
tfidf_vectorizer = TfidfVectorizer()
tfidf_matrix = tfidf_vectorizer.fit_transform(documents)

# Mendapatkan fitur (kata-kata) dari TF-IDF
tfidf_features = tfidf_vectorizer.get_feature_names_out()

# Mengonversi matriks TF-IDF menjadi DataFrame
tfidf_df = pd.DataFrame(tfidf_matrix.toarray(), columns=tfidf_features)

# Tampilkan hasil TF-IDF
print("\nHasil TF-IDF dalam bentuk DataFrame:")
tfidf_df

Hasil TF-IDF dalam bentuk DataFrame:

,abad,abai,abis,ablasi,abnormal,abu,academy,acara,ade,adenomyosis,...,youtuber,yuan,yudi,yutaka,yuwono,zaitun,zaizai,zat,zatzat,zoonosis
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.032806,0.0,0.0
96,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0
97,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.087865,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0
98,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0
99,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0

**Singular Value Decomposition (SVD)**

In [16]:
# Menggunakan SVD untuk reduksi dimensi
n_components = 99
svd = TruncatedSVD(n_components=n_components)
svd_matrix = svd.fit_transform(tfidf_matrix)

# Mengubah hasil SVD menjadi DataFrame
svd_df = pd.DataFrame(svd_matrix, columns=[f'feature {i+1}' for i in range(n_components)])
svd_df['kategori'] = news_data['kategori'].values

# Menampilkan hasil
print("Hasil reduksi dimensi dengan SVD:")
svd_df

Hasil reduksi dimensi dengan SVD:

,feature 1,feature 2,feature 3,feature 4,feature 5,feature 6,feature 7,feature 8,feature 9,feature 10,...,feature 91,feature 92,feature 93,feature 94,feature 95,feature 96,feature 97,feature 98,feature 99,kategori
0,0.106724,-0.012037,0.006242,-0.009770,0.006961,0.019942,0.030089,-0.006187,0.018838,-0.051879,...,-0.000669,-0.002871,0.005176,0.000965,-0.000955,-0.007883,-0.002486,-0.002232,0.000149,Kesehatan
1,0.266627,-0.198581,0.071352,0.392833,-0.005639,0.013603,-0.085681,0.064016,0.233886,-0.246113,...,-0.030401,0.023415,0.000721,-0.008324,0.012867,-0.003993,0.000731,0.000413,-0.001448,Kesehatan
2,0.217216,-0.111323,0.045588,-0.029127,0.085035,0.012536,0.061484,-0.029580,0.092285,-0.491121,...,-0.136141,-0.045979,-0.023626,0.032544,-0.034433,0.014400,-0.005398,-0.000738,0.000297,Kesehatan
3,0.113372,0.005862,-0.029294,-0.052294,-0.021568,-0.011935,0.016699,0.013151,-0.015687,-0.059067,...,-0.002468,0.007596,-0.006117,-0.001106,-0.010889,-0.003023,-0.003165,0.001742,-0.001530,Kesehatan
4,0.288008,-0.240852,0.122087,0.507549,-0.044444,0.010227,-0.122930,0.100639,0.245608,-0.154726,...,0.029863,-0.040212,0.000749,0.021948,-0.016247,0.002096,0.005310,0.001952,0.030341,Kesehatan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0.123232,0.068174,-0.042840,-0.034845,-0.119043,0.178695,0.002958,-0.052277,-0.038381,-0.018526,...,-0.023248,-0.005077,-0.000486,0.008559,0.000901,0.002465,0.002030,0.002874,-0.002152,Kuliner
96,0.150202,0.056783,-0.124371,-0.046811,-0.022884,0.054014,-0.029077,-0.004084,-0.068674,0.002461,...,-0.011240,-0.008200,-0.007510,0.003077,-0.003184,0.004771,0.003943,-0.003662,0.000992,Kuliner
97,0.129951,0.092993,-0.071604,-0.053881,-0.233386,0.320248,-0.035302,0.024737,0.037735,0.027366,...,0.002291,0.002315,0.000397,-0.000591,0.006479,-0.002853,0.003209,-0.001453,-0.000439,Kuliner
98,0.064543,0.002186,-0.038743,0.001043,0.017546,0.011457,-0.025084,-0.005296,0.042880,-0.029617,...,-0.002983,-0.001499,-0.006720,0.009814,-0.005959,0.002278,-0.002719,0.000269,-0.001394,Kuliner
99,0.241591,0.663417,0.316022,0.119218,0.160942,-0.023005,-0.002851,-0.029168,0.030244,0.015372,...,0.050114,0.163784,-0.007237,-0.018532,0.005647,0.022788,-0.010557,-0.055556,0.006823,Kuliner

**Implementasi**

In [17]:
def search_similar_documents(query_text, top_k=5):

    # Transformasi query text
    query_tfidf = tfidf_vectorizer.transform([query_text])
    query_svd = svd.transform(query_tfidf)

    # Hitung jarak Euclidean antara query dan dokumen
    distances = euclidean_distances(query_svd, svd_matrix)

    # Ambil indeks dokumen terdekat
    closest_indices = np.argsort(distances[0])[:top_k]
    similarities = distances[0][closest_indices]

    return closest_indices, similarities

In [18]:
# Fungsi untuk melakukan preprocessing
def preprocess_text(text):

    # Cleaning: Menghapus angka dan tanda baca
    text = re.sub(r'\d+', '', text)  # Hapus angka
    text = text.translate(str.maketrans('', '', string.punctuation))  # Hapus tanda baca

    # Casefolding: Mengubah ke huruf kecil
    text = text.lower()

    # Tokenizing
    words = word_tokenize(text)

    # Stopword removal
    stop_words = set(stopwords.words("indonesian"))  # Ganti dengan 'english' jika teks berbahasa Inggris
    words = [word for word in words if word not in stop_words]

    # Gabungkan kembali menjadi string
    return ' '.join(words)

# Input teks dan preprocessing
query_text = input("Masukkan teks: ")
processed_query_text = preprocess_text(query_text)

# Lakukan pencarian dengan teks yang telah dipreproses
top_k = 5  # Jumlah dokumen yang diinginkan
indices, distances = search_similar_documents(processed_query_text, top_k)

# Menampilkan hasil pencarian
print("\nHasil pencarian untuk query:", processed_query_text)
for idx, distance in zip(indices, distances):
    print(f"Dokumen ke-{idx + 1}: {documents[idx]}")
    print(f"Jarak Euclidean: {distance:.4f}\n")

Masukkan teks: makan

Hasil pencarian untuk query: makan
Dokumen ke-95: jakarta finalis miss hongkong ditawari makan malam bayaran mengungkap uang senilai rp miliar dijanjikan untuknya makan dunia hiburan popularitas begitupula imingiming popularitas selebriti terkenal pendatang bidang industri tersohor incarannya kontestan jebolan ajang kecantikan mendadak selebriti finalis miss hongkong mengaku tawaran aneh tawaran bertajuk makan malam bayarannya diluar dugaan baca mike tyson bugar usia menu dietnya ceci mak ditawari kencan makan malam bayaran mencapai rp miliar foto getty imagesistockphotoinside creative house ceci mak dilaporkan vn express ajakan makan malam sosok dibuka identitasnya ditawarkan uang senilai hongkong dollar setara rp miliar berujung jebakan dilaporkan hype arti kencan makan malam seringkali ditawarkan selebriti makan malam diajak restoran mewah makan malam tawaran pekerjaan mak menolak tawaran maksudnya jamuan makan malam senormalnya mengunggahnya keterangan konyol media sosialnya pekerjaan pekerjaan aktris silakan hubungi nol nomor layanan kfc hongkong mak kencan berisi tawaran pekerjaan nonselebritas meragukan foto getty imagesistockphotoinside creative house merujuk undangan makan malam imbalan seringkali korban disasar aktris selebriti wanita pendatang menjaga penggemar pengikut follower tergiur imingiming makan malam dibayar menasihatkan memblokir nomor dikenal artis tawaran modus makan malam imingiming bayaran miliaran rupiah penawaran aneh catatan mak berhatihati menerima tawaran pekerjaan terjun dunia entertain terkecoh mak tvb melaporkan tawaran sisley choi artis kelahiran malaysia diimingimingi makan malam bayaran rp miliar dflodi
Jarak Euclidean: 0.8447

Dokumen ke-81: jakarta kompilasi review codeblu menuai kehebohan ratusan warung pecel lele kamboja mltr mampir kafe konser pertamanya food vlogger hadirkan konten mereview mengulas makan salah satunya codeblu bedanya seringkali mengulas makan jujur tajam terkesan menjatuhkan ulasannya menuai kontroversi media sosial netizen x diramaikan temuan menjamurnya warung makan restoran indonesia kamboja pasalnya titik tibatiba diramaikan makan indonesia bermunculan cepat alasan baliknya grup band legendaris michael learns to rock malaysia berjarak konser pertamanya alami sulit mltr mengaku mengadakan konser kafe konser besarnya nostalgia kafe konser pertamanya malaysia berita terpopuler detikfood menarik perhatian pembaca kemarin kontroversi temuan codeblu kecoak resto tipuan timbangan supermarket foto tiktok codebluuuu kontroversi review codeblu populer kontennya mereview mengulas makanan codeblu seringkali sorotan berbeda food vlogger ulasan jujur tajam terkesan merendahkan makan codebu mengulas makan rajin mengungkap halhal menyimpang restoran makan penemuannya mengganggu ketentraman pemilik bisnis tersenggol laporannya media sosial sampaisampai klarifikasi disoroti gegara temuan laporan codeblu baca kontroversi temuan codeblu kecoak resto tipuan timbangan supermarket halaman simak video video bocoran menu warung makan milik nunung solo gambasvideo detik
Jarak Euclidean: 0.9013

Dokumen ke-63: jakarta dimabuk cinta orang rela apapun pujaan hatinya mengeluarkan uang traktir makanan dimabuk asmara orang cenderung rela apapun membahagiakan pasangan orang sukai muncul istilah budak cinta bucin dipakai menggambarkan orangorang bucin rela menghabiskan uang mentraktir pasangan makanan rutin membelikan makanan dampaknya orang kehabisan uang gaji terlilit hutang aksi bucin pasangan berkahir bikin rugi habiskan gaji pacar makan aksi bucin orang traktir makan pasangan boncos foto site news curhatan dibagikan pria malaysia akun x meinmokthar pria identitas anonim resah kebiasaan sang kekasih hobi beli makan nafsu makan menghabiskan uang rm rp juta makanan uang tersisa rm rp curhatnya memiliki kekasih nafsu makan uang habis beli makanannya pas jomblo makan sehari malaysia uang rm ratarata uang setara gaji penghasilan orang sebulan sang kekasih menghabiskan uangnya beli makanan pria pusing membandingkan pengeluaran uangnya makan jomblo pinjam uang beli es krim aksi bucin orang traktir makan pasangan boncos foto site news curhatan akun x sharing tanyarlfes pengguna x anonim membagikan kebiasaan temannya meminjam uang kebutuhan sepele salah satunya membelikan makanan kekasihnya unggahannya temannya meneruskan chat kekasihnya dibelikan es krim mcflurry mcdonalds minjem gocap rp ribu gak cepe rp ribu gue gajian gue ganti pacar gue ngajak beli gituan thr gak kerja gaji udah abis duluan gue wkwk gue minjem isi chat temannya memancing emosi netizen twitter membacanya singkat cuitan juta kali disukai ribu pengguna twitter pacar kirimkan makanan aksi bucin orang traktir makan pasangan boncos foto site news curhatan anonim x netizen kesal prilaku wanita memaksa sang pacar mengirimkan makanan rumahnya wanita sang kekasih membelikannya mie gacoan terkenal pedas sang pacar menawarkan membelikannya makanan via aplikasi ojek online uangnya menipis wanita memaksa maunya sang kekasih langsung rumahnya berargumen pacarnya membelikan makanan via aplikasi ojek online sang wanita komplain sang kekasih membelikan jenis makanan netizen geram aksi sang wanita dianggap menuntut kekasihnya suaminya halaman simak video video bocoran menu warung makan milik nunung solo gambasvideo detik
Jarak Euclidean: 0.9377

Dokumen ke-91: jakarta ramai media sosial ratusan warung makan indonesia kamboja terdeteksi google maps warung pecel lele angkringan dugaan sarang judi online mencuat kebanggaan restoran gerai makanan indonesia bertengger negeri makanan khas indonesia dikenal bersaing dunia aneh ratusan warung makan indonesia ditemukan kamboja ratusan warung makan indonesia terdeteksi google maps orang terheranheran diungkap akun x ntlfiaccount unggahannya tangkapan layar google maps kawasan bavet kamboja dipenuhi warung makan indonesia kota perbatasan terkenal redacted penjual makanan khas indo dibanding negara supply demand paham demand lokasi pictwittercomerdslpkrat ntlfiaccount november warung makan indonesia bernama pecel lele srikandi pecel lele mantul arena angkringan bakso bocil bakso gultik blok m saking banyaknya pengguna akun x kamboja negara warung makan indonesia bandingkan negara penawaran permintaan paham permintaan lokasi tulisnya unggahan dikonfirmasi detikfood samping netizen curiga kawasan dianggap netizen mengungkap kawasan sarang judi online ratusan warung pecel lele kamboja diduga sarang judi online foto x judi online melibatkan pekerja imigran indonesia kawasan warung makan indonesia masyarakat indonesia bermukim vlog menceritakan pekerjapekerja judi online kamboja mayoritas orang indonesia dikonfirmasi netizen liat dokumenter vlog youtube kaget sepesat pembangunan disana orang indo disana serem ya komenkomenan ngancem tulis netizen fyi orang indonesia bikin perusahaan judi online karyawannya orang indonesia target pasarnya orang indonesia kamboja bisnis judi online legal resmi berlisensi kbri kamboja kalo wni kerja perusahaan judi online tulis netizen rafodi
Jarak Euclidean: 0.9630

Dokumen ke-90: jakarta anjasmara kakek cucu anaknya amanda awet muda senang membagikan kebersamaan makan keluarga
Jarak Euclidean: 0.9643

****